/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3d;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Welcome to the exchanger!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int dinero,c,l,xx,x,v,ii,i;
        Scanner obx = new Scanner (System.in);
        System.out.println("Canto diñeiro queres darme?");
        dinero = obx.nextInt();
        c=dinero/100;
        l=(dinero%100)/50;
        xx=(dinero%100%50)/20;
        x=(dinero%100%50%20)/10;
        v=(dinero%100%50%20%10)/5;
        ii=(dinero%100%50%20%10%5)/2;
        i=(dinero%100%50%20%10%5%2);
        System.out.println("Billetes: \n De cien:"+c+", \n De cincuenta:"+l+", \n De veinte:"+xx+", \n De diez:"+x+", \n De cinco:"+v+", \n De dos:"+ii+", \n De una:"+i);
    }
}
