/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3e;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        double sb,st,sl,com,iv,qlm,km,irpf;
        int dieta,dd;
        Scanner obx = new Scanner (System.in);
        System.out.println("Canto e teu salario?");
        sb = obx.nextDouble();
        System.out.println("Canto vendiches este mes?");
        iv = obx.nextDouble();
        System.out.println("Cantos kilometros andaches?");
        km = obx.nextDouble();
        System.out.println("E por cantos días?");
        dd = obx.nextInt();
        
        com = iv * 0.05;
        qlm = km * 2;
        dieta = 30 * dd;
        st = sb+com+qlm+dieta;
        irpf = st * 0.18;
        sl = st-irpf-36;
        System.out.println("El sueldo total es de: "+st+" €.");
        System.out.println("El sueldo liquido es de: "+sl+" €.");
    }
}
