/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3b;
import java.util.Scanner;
public class App {
    
    public static void main(String[] args) {
        double Celsius,Fahrenheit,Kelvin;
        Scanner obx= new Scanner (System.in);
        System.out.println("Cuanto calor hace hoy?");
        Celsius = obx.nextDouble();
        Fahrenheit = Celsius*1.8+32;
        Kelvin = Celsius + 273.15;
        System.out.println("Celsius: "+Celsius+"\n Fahrenheit: "+Fahrenheit+"\n Kelvin: "+Kelvin);
    }
}
