/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3a;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Welcome to the money store!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        double tarifa, precio, descuento;
        Scanner obx = new Scanner (System.in);
        System.out.println("Cuanto era la tarifa?");
        tarifa=obx.nextDouble();
        System.out.println("Cuanto pagaste?");
        precio=obx.nextDouble();
        descuento = ((precio*100/tarifa)-100);
        System.out.println("El descuento es de :"+(-descuento));
    }
}
