/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3c;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Welcome to the money store!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int B100,B50,B20,B10,B5,M2,M1,total;
        Scanner obx = new Scanner (System.in);
        System.out.println("Cuantos de 100 quieres dar?");
        B100 = obx.nextInt()*100;
        System.out.println("Cuantos de 50 quieres dar?");
        B50 = obx.nextInt()*50;
        System.out.println("Cuantos de 20 quieres dar?");
        B20 = obx.nextInt()*20;
        System.out.println("Cuantos de 10 quieres dar?");
        B10 = obx.nextInt()*10;
        System.out.println("Cuantos de 5 quieres dar?");
        B5 = obx.nextInt()*5;
        System.out.println("Cuantas de 2 quieres dar?");
        M2 = obx.nextInt()*2;
        System.out.println("Cuantas de 1 quieres dar?");
        M1 = obx.nextInt();
        total = B100+B50+B20+B10+B5+M2+M1;
        System.out.println("Su total dado es de: "+total);
    }
}
